using rrr.VMath;

namespace rrr.Rendering;

public struct RenderVertex
{
    public Vector3f Position;
    public Vector3f Normal;
    public Vector2f UV;

    // Tangent frame for normal/bump mapping (generated by RenderMeshBuilder).
    public Vector3f Tangent;
    public float Handedness;
}