using rrr.Core;
using rrr.VMath;

namespace rrr.Rendering;

public struct RenderVertex
{
    public Vector3f Position;
    public Vector3f Normal;
    public Vector2f UV;

    // Tangent frame for normal/bump mapping (generated by RenderMeshBuilder,
    // or taken from the mesh when it supplies tangents).
    public Vector3f Tangent;
    public float Handedness;

    // Per-vertex color (defaults to white when the mesh has no vertex colors).
    public ColorRGBAf Color;
}